### ISSUE TITLE
cmd.sh is not starting

### ISSUE THREAD

**Issue by mhex** [nuls-io/nuls_2.0#302]
On a fresh install cmd.sh is not starting properly

Sometimes it hangs with the message

`waiting nuls-wallet base module ready`

stopping cmd.sh with CTRL-C and restaring gives again this message or an error

```
2019-04-16 15:24:01.277  [main] ERROR - io.nuls.rpc.modulebootstrap.RpcModule.run(RpcModule.java:196):io.nuls.rpc.modulebootstrap.Module@f852cdb5 initServer failed
java.lang.Exception: 向核心注册失败！at io.nuls.rpc.netty.processor.ResponseMessageProcessor.syncKernel(ResponseMessageProcessor.java:150) at io.nuls.rpc.modulebootstrap.RpcModule.run(RpcModule.java:186)
at io.nuls.rpc.modulebootstrap.NulsRpcModuleBootstrap.run(NulsRpcModuleBootstrap.java:87)
at io.nuls.cmd.client.CmdClientBootstrap.main(CmdClientBootstrap.java:32)

```
It works eventually after a repeated
wallet stop and start from a fresh install

**Comment by yeealbert** [comment]
问题已修复
